# Generated by Django 3.0.5 on 2020-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('telegram_chat_id', models.CharField(max_length=100)),
                ('telegram_username', models.CharField(max_length=100)),
                ('profile_photo', models.CharField(max_length=400)),
                ('faculty', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('year_of_study', models.IntegerField()),
            ],
        ),
    ]
